require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');

const products = [
  // ── Reusable Products ──────────────────────────────────────────────
  {
    name: 'Stainless Steel Water Bottle',
    price: 1899,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&q=80',
    description: 'Double-walled, vacuum-insulated 750ml bottle. Keeps drinks cold 24h and hot 12h. BPA-free, dishwasher-safe, and made with 90% recycled stainless steel.',
    ecoTag: 'Recycled',
    rating: 4.8,
    numReviews: 312,
    stock: 85,
  },
  {
    name: 'Organic Cotton Tote Bag',
    price: 749,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&q=80',
    description: 'Heavy-duty 10oz organic cotton canvas tote. Replaces over 1,000 plastic bags. Natural dye, GOTS-certified, and machine washable.',
    ecoTag: 'Organic',
    rating: 4.6,
    numReviews: 198,
    stock: 200,
  },
  {
    name: 'Bamboo Straw Set (8 Pack)',
    price: 499,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=600&fit=crop&q=80',
    description: 'Set of 8 naturally harvested bamboo straws with a cleaning brush and cotton carry pouch. Compostable at end of life. Say goodbye to plastic forever.',
    ecoTag: 'Biodegradable',
    rating: 4.4,
    numReviews: 156,
    stock: 300,
  },
  {
    name: 'Reusable Beeswax Food Wraps',
    price: 1299,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1584990347209-c248e1516a2e?w=600&h=600&fit=crop&q=80',
    description: 'Set of 3 beeswax-coated cotton wraps (S/M/L). A natural, washable, and reusable alternative to cling wrap — good for 200+ uses. Keeps food fresh longer.',
    ecoTag: 'Zero Waste',
    rating: 4.7,
    numReviews: 245,
    stock: 120,
  },
  {
    name: 'Reusable Produce Mesh Bags (6 Pack)',
    price: 849,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=600&fit=crop&q=80',
    description: 'Lightweight organic cotton mesh bags for fruits and vegetables. Tare weight printed on label. Machine washable and perfect for the farmers market.',
    ecoTag: 'Plastic Free',
    rating: 4.5,
    numReviews: 178,
    stock: 250,
  },
  {
    name: 'Glass Travel Coffee Mug',
    price: 1649,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1481833761820-0509d3217039?w=600&h=600&fit=crop&q=80',
    description: 'Borosilicate glass mug with silicone sleeve and bamboo lid. 350ml capacity, leak-proof, and microwave-safe. Stop paying the single-use cup surcharge.',
    ecoTag: 'Plastic Free',
    rating: 4.6,
    numReviews: 134,
    stock: 95,
  },

  // ── Personal Care ──────────────────────────────────────────────────
  {
    name: 'Bamboo Toothbrush Set (4 Pack)',
    price: 699,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop&q=80',
    description: 'FSC-certified bamboo handles with BPA-free charcoal-infused nylon bristles. Handle fully compostable. Switch from plastic — 3.5 billion toothbrushes are thrown away yearly.',
    ecoTag: 'Biodegradable',
    rating: 4.5,
    numReviews: 423,
    stock: 400,
  },
  {
    name: 'Plant-Based Shampoo Bar',
    price: 899,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&h=600&fit=crop&q=80',
    description: 'Concentrated solid shampoo bar equivalent to 2-3 bottles of liquid shampoo. Zero plastic packaging, sulfate-free, vegan, and suitable for all hair types.',
    ecoTag: 'Vegan',
    rating: 4.3,
    numReviews: 289,
    stock: 180,
  },
  {
    name: 'Natural Charcoal Bar Soap',
    price: 649,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1588421357574-87938a86fa28?w=600&h=600&fit=crop&q=80',
    description: 'Cold-process soap with activated charcoal, coconut oil, and lavender essential oil. Palm oil-free, cruelty-free, and wrapped in recycled kraft paper.',
    ecoTag: 'Vegan',
    rating: 4.6,
    numReviews: 312,
    stock: 220,
  },
  {
    name: 'Organic Aloe Vera Gel',
    price: 1149,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&h=600&fit=crop&q=80',
    description: 'Pure 99% organic aloe vera in a glass jar. No parabens, alcohol, or artificial fragrance. USDA-certified organic. Multi-use: moisturiser, after-sun, hair mask.',
    ecoTag: 'Organic',
    rating: 4.7,
    numReviews: 198,
    stock: 160,
  },
  {
    name: 'Organic Face Moisturiser',
    price: 2199,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&q=80',
    description: 'Lightweight daily moisturiser with organic rosehip oil, shea butter, and vitamin E. Certified organic by Ecocert. Suitable for all skin types. Refillable glass jar.',
    ecoTag: 'Organic',
    rating: 4.8,
    numReviews: 267,
    stock: 75,
  },
  {
    name: 'Compostable Dental Floss',
    price: 399,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop&q=80',
    description: 'Mulberry silk floss coated with natural candelilla wax and peppermint oil. Comes in a refillable glass vial. 30m per vial, fully compostable.',
    ecoTag: 'Compostable',
    rating: 4.2,
    numReviews: 145,
    stock: 350,
  },

  // ── Eco Home ───────────────────────────────────────────────────────
  {
    name: 'Bamboo Chopping Board',
    price: 1549,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1567225477277-c8162eb96c43?w=600&h=600&fit=crop&q=80',
    description: 'Extra-large 45×30cm Moso bamboo board. Harder than maple, naturally antimicrobial, and regenerates without replanting. Juice groove and non-slip feet included.',
    ecoTag: 'Sustainable',
    rating: 4.7,
    numReviews: 201,
    stock: 110,
  },
  {
    name: 'Natural Soy Wax Candle',
    price: 1099,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=600&fit=crop&q=80',
    description: 'Hand-poured 200g soy wax candle with cotton wick and essential oil fragrance. Burns 40h. Comes in a reusable glass jar. Vegan, non-toxic, no petroleum.',
    ecoTag: 'Vegan',
    rating: 4.6,
    numReviews: 334,
    stock: 90,
  },
  {
    name: 'Wooden Dish Brush Set',
    price: 879,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&h=600&fit=crop&q=80',
    description: 'Set of 3 FSC-beechwood brushes (dish, bottle, and pot) with sisal bristles. Naturally antibacterial. Handles are compostable. Replace plastic scrubbers for good.',
    ecoTag: 'Biodegradable',
    rating: 4.4,
    numReviews: 167,
    stock: 145,
  },
  {
    name: 'Plant-Based Laundry Tablets',
    price: 1799,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&h=600&fit=crop&q=80',
    description: '60 pre-measured laundry tablets. No liquid waste, no plastic bottle. Phosphate-free, hypoallergenic, and septic-safe. Works in all temperatures and machine types.',
    ecoTag: 'Zero Waste',
    rating: 4.5,
    numReviews: 212,
    stock: 130,
  },
  {
    name: 'Recycled Glass Vase Set',
    price: 2499,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop&q=80',
    description: 'Set of 3 mouth-blown vases crafted from 100% recycled glass. Each piece is unique — slight variations in colour and form are natural characteristics, not defects.',
    ecoTag: 'Recycled',
    rating: 4.8,
    numReviews: 89,
    stock: 40,
  },
  {
    name: 'Compost Bin for Kitchen',
    price: 2999,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=600&fit=crop&q=80',
    description: '5L stainless steel countertop compost bin with charcoal filter lid to eliminate odours. Dishwasher-safe liner. Diverts kitchen waste from landfill with zero hassle.',
    ecoTag: 'Compostable',
    rating: 4.6,
    numReviews: 178,
    stock: 65,
  },

  // ── Sustainable Fashion ────────────────────────────────────────────
  {
    name: 'Organic Cotton T-Shirt',
    price: 2299,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop&q=80',
    description: '180gsm 100% GOTS-certified organic cotton. Preshrunk, enzyme-washed for softness. Fair-trade factory in India. Sizes XS–3XL. Available in 12 earthy colours.',
    ecoTag: 'Fair Trade',
    rating: 4.5,
    numReviews: 456,
    stock: 320,
  },
  {
    name: 'Recycled Plastic Yoga Mat',
    price: 3499,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop&q=80',
    description: 'Made from 100% post-consumer recycled PET bottles. Non-slip natural rubber base. 6mm cushioning, 183×61cm. Each mat recycles approximately 25 plastic bottles.',
    ecoTag: 'Recycled',
    rating: 4.7,
    numReviews: 298,
    stock: 55,
  },
  {
    name: 'Hemp Linen Throw Blanket',
    price: 4299,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=600&h=600&fit=crop&q=80',
    description: '50% organic hemp / 50% organic linen blend. Hemp requires no pesticides and 50% less water than cotton. Softens with every wash. OEKO-TEX Standard 100 certified.',
    ecoTag: 'Organic',
    rating: 4.6,
    numReviews: 134,
    stock: 45,
  },
  {
    name: 'Sustainable Cork Sneakers',
    price: 5499,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop&q=80',
    description: 'Vegan sneakers with natural cork insoles, organic cotton upper, and natural rubber soles. No glue — entirely stitched construction. Carbon-neutral certified shipment.',
    ecoTag: 'Vegan',
    rating: 4.4,
    numReviews: 112,
    stock: 38,
  },
  {
    name: 'Upcycled Denim Backpack',
    price: 3999,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=600&fit=crop&q=80',
    description: 'Handcrafted from upcycled denim offcuts. No two bags are identical. 20L capacity, laptop sleeve up to 15", YKK zippers, and organic cotton lining.',
    ecoTag: 'Recycled',
    rating: 4.3,
    numReviews: 87,
    stock: 28,
  },

  // ── Organic Food & Wellness ────────────────────────────────────────
  {
    name: 'Organic Matcha Powder',
    price: 1999,
    category: 'Organic Food',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=600&fit=crop&q=80',
    description: 'Ceremonial-grade organic matcha from Nishio, Japan. Stone-ground, shade-grown, first harvest. Rich in L-theanine and antioxidants. 100g in a resealable tin.',
    ecoTag: 'Organic',
    rating: 4.9,
    numReviews: 567,
    stock: 95,
  },
  {
    name: 'Raw Wildflower Honey',
    price: 1649,
    category: 'Organic Food',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&q=80',
    description: 'Unfiltered, unheated wildflower honey from a single-source apiary in Himachal Pradesh. Packed with natural enzymes and pollen. 500g in a reusable glass jar.',
    ecoTag: 'Sustainable',
    rating: 4.8,
    numReviews: 289,
    stock: 70,
  },

  // ── Electronics ────────────────────────────────────────────────────
  {
    name: 'Portable Solar Power Bank',
    price: 4799,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop&q=80',
    description: '20,000mAh power bank with dual 5W foldable solar panels. Charges via solar or USB-C. 2 USB-A + 1 USB-C output. IPX5 waterproof. Made with recycled ABS casing.',
    ecoTag: 'Solar Powered',
    rating: 4.6,
    numReviews: 234,
    stock: 60,
  },

  // ── Reusable Products (new) ────────────────────────────────────────
  {
    name: 'Reusable Silicone Zip Bags (5 Pack)',
    price: 1199,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=600&h=600&fit=crop&q=80',
    description: 'BPA-free platinum silicone bags in 5 sizes. Freezer to oven safe up to 220°C. Leak-proof double zipper. Replaces 1,000+ single-use zip bags. Dishwasher safe.',
    ecoTag: 'Zero Waste',
    rating: 4.6,
    numReviews: 334,
    stock: 140,
  },
  {
    name: 'Recycled Kraft Notebook (A5)',
    price: 549,
    category: 'Reusable Products',
    image: 'https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=600&h=600&fit=crop&q=80',
    description: '160-page A5 notebook from 100% post-consumer recycled paper. Lay-flat spiral binding. Unbleached, acid-free pages. Kraft card cover with soy-ink printing.',
    ecoTag: 'Recycled',
    rating: 4.4,
    numReviews: 167,
    stock: 300,
  },

  // ── Personal Care (new) ────────────────────────────────────────────
  {
    name: 'Reusable Makeup Remover Pads (12 Pack)',
    price: 699,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop&q=80',
    description: 'Double-sided rounds — terry cloth one side, smooth cotton the other. Removes full-face makeup in one wipe. Washable 500+ times. Comes with a mesh laundry bag.',
    ecoTag: 'Zero Waste',
    rating: 4.7,
    numReviews: 389,
    stock: 220,
  },
  {
    name: 'Bamboo Safety Razor',
    price: 1599,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1621607512022-6aecc4fed814?w=600&h=600&fit=crop&q=80',
    description: 'FSC-certified bamboo handle with chrome-plated zinc head. Compatible with any standard double-edge blade. Includes 10 stainless steel blades and a recycled kraft travel case.',
    ecoTag: 'Biodegradable',
    rating: 4.5,
    numReviews: 276,
    stock: 180,
  },
  {
    name: 'Organic Cotton Face Towels (4 Pack)',
    price: 1099,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1600369671236-e74521d4f651?w=600&h=600&fit=crop&q=80',
    description: 'GOTS-certified organic cotton washcloths in ultra-soft waffle weave. 30×30cm. Gentle on sensitive skin. Replaces single-use cotton rounds. Machine washable 300+ times.',
    ecoTag: 'Organic',
    rating: 4.7,
    numReviews: 289,
    stock: 200,
  },
  {
    name: 'Natural Loofah Shower Set (3 Pack)',
    price: 799,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&h=600&fit=crop&q=80',
    description: 'Grown and harvested from the Luffa plant. Three sizes: face, body, and feet. 100% plastic-free, fully compostable. Natural alternative to synthetic scrubbers.',
    ecoTag: 'Biodegradable',
    rating: 4.3,
    numReviews: 198,
    stock: 250,
  },
  {
    name: 'Natural Beeswax Lip Balm (3 Pack)',
    price: 599,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&h=600&fit=crop&q=80',
    description: 'Three flavours: vanilla, peppermint, and unscented. Organic beeswax, shea butter, and vitamin E. Paper tube packaging — zero plastic. SPF-free, cruelty-free.',
    ecoTag: 'Organic',
    rating: 4.6,
    numReviews: 321,
    stock: 350,
  },

  // ── Eco Home (new) ─────────────────────────────────────────────────
  {
    name: 'Bamboo Laptop Stand',
    price: 2799,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop&q=80',
    description: 'Adjustable 6-angle stand crafted from FSC-certified Moso bamboo. Naturally antimicrobial, folds flat for travel. Compatible with 11–17" laptops. Improves posture and reduces desk clutter.',
    ecoTag: 'Sustainable',
    rating: 4.6,
    numReviews: 234,
    stock: 85,
  },
  {
    name: 'Wooden Mobile Phone Stand',
    price: 899,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=600&h=600&fit=crop&q=80',
    description: 'Handcrafted walnut wood stand with built-in cable management slot. Fits all phones up to 7". Press-fit joinery — no glue, no screws. Each piece carries a unique natural grain.',
    ecoTag: 'Sustainable',
    rating: 4.5,
    numReviews: 143,
    stock: 110,
  },
  {
    name: 'Coconut Shell Serving Bowls (Set of 4)',
    price: 1399,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&h=600&fit=crop&q=80',
    description: 'Hand-carved from rescued coconut shells. Each bowl is one-of-a-kind. Food-safe lacquer finish. 300ml capacity. Perfect for smoothie bowls, snacks, or décor. Zero plastic, zero waste.',
    ecoTag: 'Biodegradable',
    rating: 4.5,
    numReviews: 221,
    stock: 75,
  },
  {
    name: 'Recycled Ocean Plastic Desk Organiser',
    price: 1649,
    category: 'Eco Home',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop&q=80',
    description: '5-compartment modular organiser made from 100% post-consumer recycled ocean plastic. Add or remove sections freely. Matte finish, non-slip base. Each unit recycles 12 plastic bottles.',
    ecoTag: 'Recycled',
    rating: 4.5,
    numReviews: 178,
    stock: 95,
  },

  // ── Sustainable Fashion (new) ──────────────────────────────────────
  {
    name: 'Hemp Canvas Backpack 22L',
    price: 3299,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=600&h=600&fit=crop&q=80',
    description: '22L everyday backpack in 100% raw hemp canvas. Naturally water-resistant, stronger than cotton. Padded laptop sleeve fits 15". Brass hardware, cotton-webbing straps. Gets better with age.',
    ecoTag: 'Organic',
    rating: 4.6,
    numReviews: 198,
    stock: 60,
  },
  {
    name: 'Bamboo Sunglasses (UV400)',
    price: 2499,
    category: 'Sustainable Fashion',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop&q=80',
    description: 'Lightweight bamboo frames with polarised UV400 lenses. Natural spring hinges. Every pair has a unique grain — no two identical. Recycled cotton pouch and kraft box included. Unisex.',
    ecoTag: 'Sustainable',
    rating: 4.4,
    numReviews: 156,
    stock: 65,
  },

  // ── Organic Food (new) ─────────────────────────────────────────────
  {
    name: 'Organic Golden Milk Latte Blend',
    price: 1499,
    category: 'Organic Food',
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&h=600&fit=crop&q=80',
    description: 'Blend of organic turmeric, ashwagandha, ginger, black pepper, and coconut milk powder. 150g tin — 30 servings. No fillers, no added sugar. USDA organic certified.',
    ecoTag: 'Organic',
    rating: 4.8,
    numReviews: 412,
    stock: 90,
  },
  {
    name: 'Organic Cold-Press Coconut Oil 500ml',
    price: 1299,
    category: 'Organic Food',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&q=80',
    description: 'Single-origin, cold-pressed virgin coconut oil from Kerala. USDA organic. No bleaching or deodorising. Multi-use: cooking, hair mask, skin moisturiser. Stored in a reusable glass jar.',
    ecoTag: 'Organic',
    rating: 4.8,
    numReviews: 445,
    stock: 120,
  },
];

mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/ecostore')
  .then(async () => {
    console.log('MongoDB connected');
    await Product.deleteMany({});
    console.log(`Cleared existing products`);
    const inserted = await Product.insertMany(products);
    console.log(`✓ Seeded ${inserted.length} products across ${[...new Set(products.map(p => p.category))].length} categories`);
    process.exit(0);
  })
  .catch((err) => {
    console.error('Seed error:', err.message);
    process.exit(1);
  });
